prodList = [
	["","","Ashock Accelerator  RockPop 12oz"],
	["","","Ashock Accelerator  Cherry IcePop 12oz"],
	["","","Ashock Accelerator  Island Guava 12oz"],
	["","","Ashock Accelerator  Peach Paradise 12oz"],
	["","","Ashock Accelerator  Tropical Punch 12oz"],
	["","","Ashock Accelerator  Cherry Lime 12oz"],
	["","","Ashock Accelerator  Berry Lemonade 12oz"],
	["","","Snapple Peach Tea  32oz"],
	["","","Snapple Apple 32oz"],
	["","","Snapple Kiwi/  Strawberry 32oz"],
	["","","Snapple Mango  Madness 32oz"],
	["","","Qtea Unsweet Peach  Mango"],
	["","","Qtea Zero Cal"],
	["","","Qtea Sweet w/ Lemon"],
	["","","Qtea Lemonade"],
	["","","Qtea Sweet w/  Raspberry"],
	["","","Qtea Black w/ Mango"],
	["","","Qtea Black Sweet"],
	["","","Luzianne Sweet Tea"],
	["","","Luzianne Peach Tea"],
	["","","Liquid Death Arnold  Palmer"],
	["","","Liquid Death Peach"],
	["","","Liquid Death Grim  Leaf"],
	["","","Sparkling Ice Blue  Rasp"],
	["","","Sparkling Ice Straw  Citrus"],
	["","","Sparkling Ice Black  Rasp"],
	["","","Sparkling Ice  Cherry Vanilla"],
	["","","Sparkling Ice  Tropical"],
	["","","Gold Peak Sweet"],
	["","","Gold Peak Unsweet"],
	["","","Gold Peak Green"],
	["","","Gold Peak Peach"],
	["","","Arizona Green"],
	["","","Arizona Mango"],
	["","","Arizona Watermelon"],
	["","","Arizona Arnold  Palmer"],
	["","","Arizona Sweet Tea"],
	["","","Peace Razzleberry"],
	["","","Peace Caddy Shack"],
	["","","Peace Peachy"],
	["","","Pure Leaf Sweet"],
	["","","Pure Leaf Extra  Sweet"],
	["","","Pure Leaf Unsweet"],
	["","","Pure Leaf Lemon"],
	["","","Lipton Green Citrus"],
	["","","Lipton Peach"],
	["","","Lipton Green Citrus  Dt"],
	["","","Snapple Peach 16oz"],
	["","","Snapple Kiwi/  Strawberry 16oz"],
	["","","Snapple Fruit Punch  16oz"],
	["","","Jarritos Mineragua"],
	["","","Jarritos Sangria"],
	["","","Jarritos Manzania"],
	["","","Jarritos Manderin"],
	["","","Jarritos Strawberry"],
	["","","Jarrritos Pineapple"],
	["","","Brisk Sweet"],
	["","","Brisk Strawberry  Melon"],
	["","","Brisk Raspberry"],
	["","","Brisk Green w/  Peach"],
	["","","Brisk Sweet w/  Lemon"],
	["","","Vitamin Water  Energy 20oz"],
	["","","Vitamin Water Power  C 20oz"],
	["","","Vitamin Water XXX  20oz"],
	["","","Vitamin Water  Refresh 20oz"],
	["","","Vitamin Water  Essential 20oz"],
	["","","Vitamin Water XXX  Zero 20oz"],
	["","","Vitamin Water Gutzy  Zero 20oz"],
	["","","Vitamin Water  Forever Zero 20oz"],
	["","","Powerade Mountain  Blast 20oz"],
	["","","Powerade Fruit  Punch 20oz"],
	["","","Powerade Mountain  Blast 28oz"],
	["","","Powerade Fruit  Punch 28oz"],
	["","","Powerade Grape 28oz"],
	["","","Powerade Lemon Lime  28oz"],
	["","","Powerade Island  Burst 28oz"],
	["","","Powerade Orange  28oz"],
	["","","Powerade Strawberry  Lemon 28oz"],
	["","","Powerade Mixed  Berry Zero 28oz"],
	["","","Powerade Strawberry  Smash Zero 28oz"],
	["","","Powerade Grape Zero  28oz"],
	["","","Body Armor Flash  Straw/ Kiwi 20oz"],
	["","","Body Armor Flash  Tropical 20oz"],
	["","","Body Armor Flash  Grape 20oz"],
	["","","Body Armor Flash  Orange 20oz"],
	["","","Body Armor Straw  Banana 16oz"],
	["","","Body Armor Orange  Mango 16oz"],
	["","","Body Armor Fruit  Punch 16oz"],
	["","","Body Armor Lemon  Lime Lt 28oz"],
	["","","Body Armor Fruit  Punch Zero 28oz"],
	["","","Body Armor Orange  Zero 28oz"],
	["","","Body Armor Peach  Mango Lt 28oz"],
	["","","Body Armor Straw  Banana 28oz"],
	["","","Body Armor Fruit  Punch 28oz"],
	["","","Body Armor Orange  Mango 28oz"],
	["","","Body Armor Passion  Fruit 28oz"],
	["","","Body Armor Cherry  Lime 28oz"],
	["","","Body Armor Tropical  28oz"],
	["","","Body Armor  Strawberry Grape 28oz"],
	["","","Body Armor Blue  Raspberry 28oz"],
	["","","Body Armor Blackout  Berry 28oz"],
	["","","Vitamin Water XXX  32oz"],
	["","","Vitamin Water  Refresh 32oz"],
	["","","Vitamin Water Power  C 32oz"],
	["","","Vitamin Water  Energy 32oz"],
	["","","Gatorade Cool Blue  20oz"],
	["","","Gatorade Fruit  Punch 20oz"],
	["","","Gatorade Lemon Lime  20oz"],
	["","","Gatorlyte Orange  20oz"],
	["","","Gatorade Glacier  Freeze 20oz"],
	["","","Gatorade Glacier  Cherry 20oz"],
	["","","Gatorade Glacier  Freeze Zero 20oz"],
	["","","Gatorade Glacier  Cherry Zero 20oz"],
	["","","Gatorlyte Orange  20oz"],
	["","","Gatorlyte  Strawberry Kiwi 20oz"],
	["","","Gatorlyte Cherry  Lime 20oz"],
	["","","Gatorlyte Glacier  Freeze 20oz"],
	["","","Gatorlyte Mix Berry  20oz"],
	["","","Gatorlyte Lemon  Lime 20oz"],
	["","","Gatorlyte Fruit  Punch 20oz"],
	["","","Gadorade Gfit  Water/ Straw 16.9oz"],
	["","","Gadorade Gfit  Tropical Mango 16.9oz"],
	["","","Gatorade Glacier  Freeze Zero 28oz"],
	["","","Gatorade Lemon Lime  Zero 28oz"],
	["","","Gatorade Orange  Zero 28oz"],
	["","","Gatorade Berry Zero  28oz"],
	["","","Gatorade Glacier  Cherry Zero 28oz"],
	["","","Gatorade Cool Blue  Zero 28oz"],
	["","","Gatorade Grape Zero  28oz"],
	["","","Gatorade Cool Blue  28oz"],
	["","","Gatorade Fruit  Punch 28oz"],
	["","","Gatorade Lemon Lime  28oz"],
	["","","Gatorade Orange  28oz"],
	["","","Gatorade Glacier  Freeze 28oz"],
	["","","Gatorade Glacier  Cherry 28oz"],
	["","","Gatorade Arctic  Blitz 28oz"],
	["","","Gatorade Fierce  Grape 28oz"],
	["","","Gatorade Cucumber  Lime 28oz"],
	["","","Gatorade Blue  Cherry 28oz"],
	["","","Gatorade Cool Blue  24oz"],
	["","","Gatorade Fruit  Punch 24oz"],
	["","","Gatorade Lemon Lime  24oz"],
	["","","Gatorade Glacier  Cherry 24oz"],
	["","","Celsius Tropical  Vibe 12oz"],
	["","","Celsius Peach Vibe  12oz"],
	["","","Celsius Arctic Vibe  12oz"],
	["","","Celsius Fantasy  Vibe 12oz"],
	["","","Celsius Raspberry  Asai 12oz"],
	["","","Celsius Kiwi Guava  12oz"],
	["","","Celsius Strawberry  Lemon 12oz"],
	["","","Celsius Watermelon  12oz"],
	["","","Celsius Peach Mango  12oz"],
	["","","Celsius Orange 12oz"],
	["","","Celsius Grape Rush  12oz"],
	["","","Celsius Lemon Lime  12oz"],
	["","","Celsius Fuji Apple  Pear 12oz"],
	["","","Celsius Wild Berry  12oz"],
	["","","Celsius Strawberry  Guava 12oz"],
	["","","Nocco Juicy Breeze"],
	["","","Nocco Caribbean"],
	["","","Nocco Tropical"],
	["","","Nocco Miami"],
	["","","Nocco Blood Orange"],
	["","","Ashock Accelerator  RockPop 12oz"],
	["","","Ashock Accelerator  Cherry IcePop 12oz"],
	["","","Ashock Accelerator  Island Guava 12oz"],
	["","","Ashock Accelerator  Peach Paradise 12oz"],
	["","","Ashock Accelerator  Tropical Punch 12oz"],
	["","","Ashock Accelerator  Cherry Lime 12oz"],
	["","","Ashock Accelerator  Berry Lemonade 12oz"],
	["","","Ashock Tropical  Punch 16oz"],
	["","","Ashock Blue Razz  16oz"],
	["","","Ashock Orange  Freeze 16oz"],
	["","","Java Monster Mean  Bean 15oz"],
	["","","Java Monster Loca  Mocha 15oz"],
	["","","Java Monster Irish  Blend 15oz"],
	["","","Java Monster Salted  Caramel 15oz"],
	["","","Java Monster Café  Latte 15oz"],
	["","","Dunkin' Brownie  Batter 11oz"],
	["","","Dunkin' Cake Batter  11oz"],
	["","","Black Rifle 300  Mocha 15oz"],
	["","","Black Rifle 300  Caramel Vanilla 15oz"],
	["","","Black Rifle 300  Vanilla Bomb 15oz"],
	["","","Black Rifle Mocha  11oz"],
	["","","Black Rifle Cream  11oz"],
	["","","Java Monster 300  Mocha 15oz"],
	["","","Java Monster 300  Vanilla 15oz"],
	["","","Dunkin' Donuts  Mocha 13.7oz"],
	["","","Dunkin' Donuts  Vanilla 13.7oz"],
	["","","Dunkin' Donuts  Caramel 13.7oz"],
	["","","Super Coffee Mocha  12oz"],
	["","","Super Coffee  Vanilla 12oz"],
	["","","Super Coffee  Caramel 12oz"],
	["","","Starbucks White  Chocolate 15oz"],
	["","","Starbucks Coffee  15oz"],
	["","","Starbucks TS Mocha  15oz"],
	["","","Starbucks TS  Vanilla 15oz"],
	["","","Costa Coffee Mocha"],
	["","","Costa Coffee  Caramel"],
	["","","Int. Delight  Caramel 15oz"],
	["","","Int. Delight Oreo  15oz"],
	["","","Int. Delight  Reese's 15oz"],
	["","","Starbucks Frap  Coffee 13.7oz"],
	["","","Starbucks Frap  Caramel 13.7oz"],
	["","","Starbucks Mocha  15oz"],
	["","","Starbucks Vanilla  15oz"],
	["","","Starbucks DS 6.5oz"],
	["","","Starbucks Frap  White Choc 13.7oz"],
	["","","Starbucks Frap  Mocha 13.7oz"],
	["","","Starbucks Frap  Vanilla 13.7oz"],
	["","","C4 Smart Strawberry  Guava 12oz"],
	["","","C4 Smart  Cherryberry Lime 12oz"],
	["","","C4 Ultra Arctic  Snow Cone 16oz"],
	["","","C4 Ultra Fruit  Punch 16oz"],
	["","","C4 Ultra Orange  Cream 16oz"],
	["","","C4 Ultra Raspberry  16oz"],
	["","","C4 Ultra Berry Bomb  16oz"],
	["","","C4 Ultra Freedom  Ice 16oz"],
	["","","C4 Starburst  Strawberry 16oz"],
	["","","C4 Skittles 16oz"],
	["","","C4 Frozen Bombsicle  16oz"],
	["","","C4 Midnight Cherry  16oz"],
	["","","C4 Cherry Popsicle  16oz"],
	["","","C4 Grape Popsicle  16oz"],
	["","","C4 Hawaiian Pine  16oz"],
	["","","C4 Watermelon 16oz"],
	["","","C4 Orange Slice  16oz"],
	["","","C4 Mango Foxtrot  16oz"],
	["","","Amino Grape 12oz"],
	["","","Amino Blueberry  Lemonade 12oz"],
	["","","Amino Berry Burst  12oz"],
	["","","Amino Orange 12oz"],
	["","","Amino Cherry 12oz"],
	["","","Amino Mango 12oz"],
	["","","Amino Strawberry  12oz"],
	["","","Amino Peach 12oz"],
	["","","Amino Watermelon  12oz"],
	["","","Bang Peach Mango"],
	["","","Bang Blue Razz"],
	["","","Bang Purple Haze"],
	["","","Bang Black Cherry  Vanilla"],
	["","","Bang Star Blast"],
	["","","Bang Cotton Candy"],
	["","","Bang Strawberry"],
	["","","Bang Sour Head"],
	["","","Bang Radical  Skadattle"],
	["","","Bang Watermelon"],
	["","","Reign Orange  Dreamsicle 16oz"],
	["","","Reign Tropical  Storm 16oz"],
	["","","Reign Sour Gummy  Worm 16oz"],
	["","","Reign Rainbow  Sherbet 16oz"],
	["","","Reign White Gummy  Bear 16oz"],
	["","","Reign Razzle Berry  16oz"],
	["","","Reign Cherry  Limeaid 16oz"],
	["","","Reign Storm Kiwi  12oz"],
	["","","Reign Storm Grape  12oz"],
	["","","Reign Storm Orange  12oz"],
	["","","Reign Storm Guava  Straw 12oz"],
	["","","Reign Storm Citrus  12oz"],
	["","","Ryse Kool-Aid"],
	["","","Ryse Sunny D"],
	["","","Ryse Ring Pop"],
	["","","Ryse Country Time  Lemonade"],
	["","","Ryse Baja Burst"],
	["","","Alani Cherry Twist  12oz"],
	["","","Alani Juicy Peach  12oz"],
	["","","Alani Cherry Slush  12oz"],
	["","","Alani Cosmic Star  12oz"],
	["","","Xyience Cherry Lime"],
	["","","Xyience Mango Guava"],
	["","","Xyience Frostberry  Blast"],
	["","","Xyience Blue Pom"],
	["","","Xyience Fuji Apple"],
	["","","Xyience Fruit Punch"],
	["","","QT Energy 16oz"],
	["","","QT Energy Blue 16oz"],
	["","","QT Energy Ultra  Zero 16oz"],
	["","","Rooster Booster  16oz"],
	["","","Rooster Booster  Lite 16oz"],
	["","","1Phorm Scrmin'  Freedom 16oz"],
	["","","1Phorm Blue  Raspberry 16oz"],
	["","","1Phorm Citrus 16oz"],
	["","","1Phorm Sunrise 16oz"],
	["","","1Phorm Tropical  16oz"],
	["","","Bucked Miami 16oz"],
	["","","Bucked Rocket 16oz"],
	["","","Bucked Raspberry  16oz"],
	["","","Bucked White Gummy  16oz"],
	["","","Rockstar Zero  Silver Ice 16oz"],
	["","","Rockstar Zero  Punched 16oz"],
	["","","Rockstar Sugar Free  16oz"],
	["","","Rockstar Zero  Strawberry Peach 16oz"],
	["","","Rockstar Strawberry  Peach 16oz"],
	["","","Gatorade Twitch  Strawberry"],
	["","","Gatorade Twitch  Cool Blue"],
	["","","Mountain Dew AMP  16oz"],
	["","","Rockstar Energy  16oz"],
	["","","Rockstar Punched  16oz"],
	["","","Rockstar Recovery  Orange 16oz"],
	["","","Rockstar Recovery  16oz"],
	["","","Monster Energy  19.2oz"],
	["","","Monster Zero Ultra  19.2oz"],
	["","","Monster Mango Loco  19.2oz"],
	["","","Monster Rehab  18.6oz"],
	["","","Monster Zero Sugar  16oz"],
	["","","Monster Lo-Carb  16oz"],
	["","","Monster Nitro Super  Dry 16oz"],
	["","","1Monster Energy 16oz"],
	["","","Monster Ultra  Strawberry 16oz"],
	["","","Monster Energy 12oz"],
	["","","Monster Zero Ultra  12oz"],
	["","","Monster Ultra Ruby  Red 12oz"],
	["","","Monster Ultra  Sunrise 12oz"],
	["","","Monster Ultra  Strawberry 12oz"],
	["","","Monster Zero Ultra  16oz"],
	["","","Monster Ultra Ruby  Red 16oz"],
	["","","Monster Ultra  Sunrise 16oz"],
	["","","Monster Ultra  Peachy Keen 16oz"],
	["","","Monster Ultra  Violet 16oz"],
	["","","Monster Ultra  Paradise 16oz"],
	["","","Monster Ultra  Watermelon 16oz"],
	["","","Monster Ultra  Fiesta Mango 16oz"]
]

for a in prodList:
	if len(a) != 3:
		break
	print(*a,sep=" : ",end="\n")
	mySplit = a[2].split(" ")
	print(mySplit)
	newStr=""

	idx=0
	cntr=0

	while idx <= len(mySplit)-1:
		if mySplit[idx] != "":
			newStr=f"{newStr}{(sep:="\n" if (cntr+len(mySplit[idx])+1 >= 26 and a[2].find("\n") < 0) or (len(a[2]) >= 26 and idx == len(mySplit)-2 and a[2].find("\n") < 0) else "")}{mySplit[idx]}{" " if idx < len(mySplit)-1 else ""}"
			print(f"|{newStr}|")
			cntr = 0 if sep == "\n" else cntr+len(mySplit[idx])+1
		idx+=1
	a[2] = newStr
	print(a[2])
	print()
